FROM ubuntu:18.04
RUN apt-get update && apt-get install -y build-essential python2.7-dev
WORKDIR /work
RUN useradd -ms /bin/bash coll
RUN rm -rf /work
ENV DEBIAN_FRONTEND=noninteractive

#COPY --from=fuzzer-libfuzzer:binutils --chown=coll:coll /targets/libfuzzer-binutils /targets/binutils
#COPY --from=fuzzer-libfuzzer:lava --chown=coll:coll /targets/libfuzzer-lava /targets/lava
RUN apt-get update && apt-get install -y libarchive-dev libglib2.0 libgss3
COPY --from=fuzzer-libfuzzer:google --chown=coll:coll /targets/google /targets/google

WORKDIR /home/coll
USER coll
