FROM ubuntu:18.04
RUN apt-get update && apt-get install -y build-essential python2.7-dev
WORKDIR /work
RUN useradd -ms /bin/bash coll
COPY --from=fuzzer-system:afl --chown=coll:coll /work /work
RUN cd afl && make install
RUN rm -rf /work
ENV DEBIAN_FRONTEND=noninteractive

COPY --from=fuzzer-afl:binutils --chown=coll:coll /targets/afl-binutils /targets/binutils
COPY --from=fuzzer-afl:lava --chown=coll:coll /targets/afl-lava /targets/lava
RUN apt-get update && apt-get install -y libarchive-dev libglib2.0 libgss3
COPY --from=fuzzer-afl:google --chown=coll:coll /targets/afl-google /targets/google

WORKDIR /home/coll
USER coll
