FROM ubuntu:16.04
#FROM fuzzer-system

USER root

RUN apt-get update && apt-get install -y git build-essential wget clang

RUN mkdir -p /work/qsym
WORKDIR /work/qsym
COPY minimizer-path.patch /work/qsym/minimizer-path.patch

RUN git clone https://github.com/sslab-gatech/qsym.git qsym-base
WORKDIR /work/qsym/qsym-base
RUN git apply ../minimizer-path.patch

COPY setup.sh /work/qsym/qsym-base/setup.sh
RUN ./setup.sh
RUN pip install --upgrade pip 
RUN pip install "pytest<5"
RUN pip install . --upgrade
RUN cd tests/; python build.py
COPY --from=fuzzer-system:afl /work/afl/ /fuzzers/afl
