FROM ubuntu:18.04
#FROM fuzzer-system

USER root

RUN apt-get update && apt-get install -y git build-essential wget clang python python-pip gcc-4.8-multilib g++-4.8-multilib
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 10
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 10

RUN mkdir -p /work/qsym
WORKDIR /work/qsym
COPY minimizer-path.patch /work/qsym/minimizer-path.patch

RUN git clone https://github.com/sslab-gatech/qsym.git qsym-base
WORKDIR /work/qsym/qsym-base
RUN git apply ../minimizer-path.patch

COPY setup.sh /work/qsym/qsym-base/setup.sh
RUN ./setup.sh
#RUN pip install --upgrade pip 
RUN pip install "pytest<5"
RUN pip install . --upgrade
RUN cd tests/; python build.py
COPY --from=fuzzer-system:afl /work/afl/ /fuzzers/afl
