FROM fuzzer-system:qsym

RUN useradd -ms /bin/bash coll

RUN apt-get update && apt-get install -y cmake rsync clang-6.0 build-essential software-properties-common 
RUN update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 100 && \
update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-6.0 1000 && \
update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 100  && \
update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 100 && \
update-alternatives --install /usr/bin/clang clang /usr/bin/clang-6.0 1000 

RUN add-apt-repository -y ppa:longsleep/golang-backports && apt-get update && apt-get install -y golang-go
RUN go get github.com/SRI-CSL/gllvm/cmd/...

RUN apt-get update && apt-get install -y wget make build-essential gcc libbfd-dev libunwind-dev binutils-dev git libtool libtool-bin automake bison libglib2.0-dev python python-pip cmake curl libc-ares-dev libfreetype6-dev libarchive-dev ragel bzip2 libgss-dev subversion libgcrypt-dev autoconf-archive virtualenv libdbus-glib-1-dev libgirepository1.0-dev libturbojpeg libssh-dev libssl-dev nasm libbz2-dev libxml2-dev software-properties-common libacl1-dev

RUN apt-get update && apt-get install lzma-dev liblzma-dev

ENV CC=clang
ENV CXX=clang++

WORKDIR  /work
# build fuzzer-test-suite
RUN wget http://releases.llvm.org/9.0.0/compiler-rt-9.0.0.src.tar.xz -O compiler-rt.tar.xz && ls -lah && tar xfv compiler-rt.tar.xz
RUN git clone https://github.com/google/fuzzer-test-suite.git && cd fuzzer-test-suite && git checkout b2e885706d6
COPY --chown=coll:coll build.sh fuzzer-test-suite/build.sh
RUN mkdir build-test-suite
COPY --chown=coll:coll build_fuzzer_test_suite.py build-test-suite/build_fuzzer_test_suite.py
RUN cd build-test-suite  && FUZZING_ENGINE=afl python build_fuzzer_test_suite.py
RUN mkdir build-test-suite-plain
COPY --chown=coll:coll build_fuzzer_test_suite.py build-test-suite-plain/build_fuzzer_test_suite.py
RUN cd build-test-suite-plain  && FUZZING_ENGINE=coverage python build_fuzzer_test_suite.py
RUN mkdir -p /targets/google
RUN mkdir -p /targets-plain/google
#RUN find build-test-suite -name "*-afl" -executable | xargs cp -t  /targets/afl-google/
RUN rsync -avr --exclude=RUNDIR-*/BUILD --exclude=RUNDIR-*/SRC build-test-suite/RUNDIR-* /targets/google
RUN rsync -avr --exclude=RUNDIR-*/BUILD --exclude=RUNDIR-*/SRC build-test-suite-plain/RUNDIR-* /targets-plain/google
