FROM ubuntu:18.04
RUN apt-get update && apt-get install -y build-essential
WORKDIR /work
RUN useradd -ms /bin/bash coll
ENV DEBIAN_FRONTEND=noninteractive

RUN mkdir /targets
COPY --from=fuzzer-plain:binutils --chown=coll:coll /targets/binutils /targets/binutils
COPY --from=fuzzer-plain:lava --chown=coll:coll /targets/lava /targets/lava
RUN apt-get update && apt-get install -y libarchive-dev libglib2.0 libgss3
COPY --from=fuzzer-plain:google --chown=coll:coll /targets/google /targets/google


WORKDIR /home/coll
USER coll

