FROM fuzzer-system:honggfuzz

ENV CC=hfuzz-clang
ENV CXX=hfuzz-clang++

# build binutils 
WORKDIR  /work
RUN mkdir -p /targets/honggfuzz-binutils

RUN wget https://ftp.gnu.org/gnu/binutils/binutils-2.31.1.tar.gz && tar xfv binutils-2.31.1.tar.gz

RUN cd binutils-2.31.1/ && ./configure --prefix=/targets/honggfuzz-binutils/ && make -j`nproc` && make install
