FROM fuzzer-system

USER root
WORKDIR /work

RUN apt-get update && apt-get install -y python2.7-dev python3.7-dev libpixman-1-dev
# install AFL++ 
RUN git clone https://github.com/vanhauser-thc/AFLplusplus.git && cd AFLplusplus && git checkout tags/2.60c && make distrib && make -j`nproc` && cd llvm_mode && make -j`nproc` && cd ../ && make install

