FROM fuzzer-system:aflplusplus

ENV CC=clang
ENV CXX=clang++

WORKDIR  /work
# build fuzzer-test-suite
RUN wget http://releases.llvm.org/9.0.0/compiler-rt-9.0.0.src.tar.xz -O compiler-rt.tar.xz && ls -lah && tar xfv compiler-rt.tar.xz
#RUN git clone https://github.com/google/fuzzer-test-suite.git && cd fuzzer-test-suite && git checkout b2e885706d6
RUN git clone https://github.com/google/fuzzer-test-suite.git && cd fuzzer-test-suite
COPY --chown=coll:coll build.sh fuzzer-test-suite/build.sh
COPY --chown=coll:coll aflplusplus-google.patch fuzzer-test-suite/aflplusplus-google.patch
RUN cd fuzzer-test-suite && git apply aflplusplus-google.patch
RUN mkdir build-test-suite
COPY --chown=coll:coll build_fuzzer_test_suite.py build-test-suite/build_fuzzer_test_suite.py
RUN cd build-test-suite && python build_fuzzer_test_suite.py
RUN mkdir /targets/aflplusplus-google
RUN find . -name "*-afl" -executable | xargs cp -t  /targets/aflplusplus-google/
#RUN cp -r build-test-suite/RUNDIR-*/seeds /inputs/google
RUN apt-get update && apt-get install -y rsync
RUN rsync -avr --exclude=RUNDIR-*/BUILD --exclude=RUNDIR-*/SRC build-test-suite/RUNDIR-* /targets/aflplusplus-google
